[package]

name = "smtp"
version = "0.0.2"
authors = ["Alexis Mousset <contact@amousset.eu>"]
description = "Simple SMTP client and library"

documentation = "http://amousset.github.io/rust-smtp/smtp/"
repository = "https://github.com/amousset/rust-smtp"

license = "MIT/Apache-2.0"
readme = "README.md"

keywords = ["email", "smtp"]

[dependencies]
time = "*"
