[package]

name = "lettre"
version = "0.5.2"
description = "Email client"
readme = "README.md"
documentation = "http://lettre.github.io/lettre/"
repository = "https://github.com/lettre/lettre"
homepage = "http://lettre.github.io/"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
bufstream = "0.1"
email = "0.0"
log = "0.3"
openssl = "0.7"
rustc-serialize = "0.3"
rust-crypto = "0.2"
time = "0.1"
uuid = "0.1"

[dev-dependencies]
env_logger = "0.3"

[features]
unstable = []
