[package]
name = "lettre"
version = "0.9.2" # remember to update html_root_url
description = "Email client"
readme = "README.md"
homepage = "http://lettre.at"
repository = "https://github.com/lettre/lettre"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
categories = ["email"]
keywords = ["email", "smtp", "mailer"]
edition = "2018"

[badges]
travis-ci = { repository = "lettre/lettre" }
appveyor = { repository = "lettre/lettre" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "lettre/lettre" }
is-it-maintained-open-issues = { repository = "lettre/lettre" }

[dependencies]
log = "^0.4"
nom = { version = "^5.0", optional = true }
bufstream = { version = "^0.1", optional = true }
native-tls = { version = "^0.2", optional = true }
base64 = { version = "^0.11", optional = true }
hostname = { version = "^0.2", optional = true }
serde = { version = "^1.0", optional = true, features = ["derive"] }
serde_json = { version = "^1.0", optional = true }
fast_chemail = "^0.9"
r2d2 = { version = "^0.8", optional = true }
email = { version = "^0.0.20", optional = true }
mime = { version = "^0.3", optional = true }
time = { version = "^0.1", optional = true }
uuid = { version = "^0.8", features = ["v4"], optional = true }

[dev-dependencies]
env_logger = "^0.7"
glob = "^0.3"
criterion = "^0.3"

[[bench]]
name = "transport_smtp"
harness = false

[features]
default = ["file-transport", "smtp-transport", "sendmail-transport", "builder"]
builder = ["email", "mime", "time", "base64", "uuid"]
unstable = []
serde-impls = ["serde"]
file-transport = ["serde-impls", "serde_json"]
smtp-transport = ["bufstream", "native-tls", "base64", "nom", "hostname"]
sendmail-transport = []
connection-pool = ["r2d2"]

[[example]]
name = "smtp"
required-features = ["smtp-transport"]

[[example]]
name = "smtp_gmail"
required-features = ["smtp-transport"]

[[example]]
name = "builder"
required-features = ["builder"]