[package]

name = "smtp"
version = "0.0.12"
description = "Simple SMTP client"
readme = "README.md"
documentation = "http://amousset.github.io/rust-smtp/smtp/"
repository = "https://github.com/amousset/rust-smtp"
homepage = "https://github.com/amousset/rust-smtp"
license = "MIT/Apache-2.0"
authors = ["Alexis Mousset <contact@amousset.me>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
time = "*"
uuid = "*"
log = "*"
rustc-serialize = "*"
rust-crypto = "*"

[dev-dependencies]
env_logger = "*"
