[package]

name = "smtp"
version = "0.0.15"
description = "Simple SMTP client"
readme = "README.md"
documentation = "http://amousset.github.io/rust-smtp/smtp/"
repository = "https://github.com/amousset/rust-smtp"
homepage = "https://github.com/amousset/rust-smtp"
license = "MIT/Apache-2.0"
authors = ["Alexis Mousset <contact@amousset.me>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
time = "0.1"
uuid = "0.1"
log = "0.3"
rustc-serialize = "0.3"
rust-crypto = "0.2"
bufstream = "0.1"
email = "*"

[dev-dependencies]
env_logger = "*"

[features]
unstable = []
