[package]

name = "lettre"
version = "0.7.0"
description = "Email client"
readme = "README.md"
documentation = "https://docs.rs/lettre/"
repository = "https://github.com/lettre/lettre"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
categories = ["email"]
keywords = ["email", "smtp", "mailer"]

[badges]
travis-ci = { repository = "lettre/lettre" }

[dependencies]
bufstream = "^0.1"
log = "^0.3"
native-tls = "^0.1"
base64 = "^0.6"
hex = "^0.2"
rust-crypto = "^0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
emailaddress = "^0.4"

[dev-dependencies]
env_logger = "^0.4"

[features]
unstable = []
